baseURL = 'https://khelben.github.io/artware.be-hugo/'
languageCode = 'nl-be'
title = 'ARTware - Keramiek'

[params]
logo = './images/logo.png'


[caches]
  [caches.images]
    dir = ':cacheDir/images'
